# Generated by Django 2.2.3 on 2019-07-29 13:50

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(blank=True, upload_to='projects_images', verbose_name='avatar')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('date_created', models.DateField(default=datetime.date(2019, 7, 29), verbose_name='creation date')),
                ('content', models.CharField(max_length=512, verbose_name='content')),
                ('like', models.BooleanField(default=False, verbose_name='like/unlike')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectUser', verbose_name='author')),
            ],
        ),
    ]
